# Generated by Django 5.2.4 on 2025-07-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent_Product', '0003_cliente_proveedor_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_proveedor',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
